name: 'Commit Linter'
description: 'Lints Pull Request commit messages with commitlint'
author: 'Wagner Santos'
inputs:
  configFile:
    description: 'commitlint config file'
    default: './commitlint.config.js'
runs:
  using: 'docker'
  image: 'docker://wagoid/commitlint-github-action:1.1.1'
branding:
  icon: 'check-square'
  color: 'blue'
