name: Commitlint
on: [pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - run: sed -i -E "s/([']docker:.+)/Dockerfile/" ./action.yml
      - uses: ./
  commitlint-with-yml-file:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - run: sed -i -E "s/([']docker:.+)/Dockerfile/" ./action.yml
      - uses: ./
        with:
          configFile: './.commitlintrc.yml'
  commitlint-with-lerna-scopes:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - run: sed -i -E "s/([']docker:.+)/Dockerfile/" ./action.yml
      - uses: ./
        with:
          configFile: './.commitlintrc-with-lerna-scopes.yml'
